services:
    mysql:
        image: mysql:8.0
        ports:
            - "3309:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root_password_secret_tcp
            - MYSQL_DATABASE=thinkflow-db
        volumes:
            - mysql:/var/lib/mysql
            - ./data.sql:/docker-entrypoint-initdb.d/data.sql
        networks:
            - thinkflow
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

    nats:
        image: nats:2.10.11
        ports:
            - "4222:4222"
            - "8222:8222"
        environment:
            - NATS_SERVER=${NATS_SERVER}
            - NATS_USERNAME=${NATS_USERNAME}
            - NATS_PASSWORD=${NATS_PASSWORD}
            - NATS_TOKEN=${NATS_TOKEN}
        networks:
            - thinkflow
        healthcheck:
            test: ["CMD", "nats-server", "--help"]
            timeout: 5s
            retries: 5

    redis:
        image: redis:7.4-alpine
        ports:
            - "6380:6379"
        volumes:
            - redis:/data
        networks:
            - thinkflow
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            timeout: 5s
            retries: 5

    auth-service:
        build: ./auth-service
        environment:
            - APP_NAME=thinkflow-auth
            - CLIENT_URL=https://thinkflow-web.vercel.app
            - DB_DSN=root:root_password_secret_tcp@tcp(mysql:3306)/thinkflow-auth?charset=utf8mb4&parseTime=True&loc=Local
            - GIN_PORT=3100
            - GRPC_PORT=3101
            - GRPC_USER_ADDRESS=user-service:3201
            - JWT_SECRET=very-important-please-change-it!
            - EMAIL_USER=${EMAIL_USER}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - REDIS_ADDRESS=redis:6379
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
            - GOOGLE_USER_INFO_URL=${GOOGLE_USER_INFO_URL}
            - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
            - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
            - FACEBOOK_REDIRECT_URL=${FACEBOOK_REDIRECT_URL}
            - FACEBOOK_GRAPH_ME_URL=${FACEBOOK_GRAPH_ME_URL}
        networks:
            - thinkflow
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy

    user-service:
        build: ./user-service
        environment:
            - DB_DSN=root:root_password_secret_tcp@tcp(mysql:3306)/thinkflow-users?charset=utf8mb4&parseTime=True&loc=Local
            - GIN_PORT=3200
            - GRPC_PORT=3201
            - GRPC_AUTH_ADDRESS=auth-service:3101
            - GRPC_NOTE_ADDRESS=note-service:3301
            - GRPC_MEDIA_ADDRESS=media-service:3401
        networks:
            - thinkflow
        depends_on:
            mysql:
                condition: service_healthy

    note-service:
        build: ./note-service
        environment:
            - CLIENT_URL=https://thinkflow-web.vercel.app/
            - DB_DSN=root:root_password_secret_tcp@tcp(mysql:3306)/thinkflow-notes?charset=utf8mb4&parseTime=True&loc=Local
            - GIN_PORT=3300
            - GRPC_PORT=3301
            - GRPC_AUTH_ADDRESS=auth-service:3101
            - GRPC_USER_ADDRESS=user-service:3201
            - GRPC_MEDIA_ADDRESS=media-service:3401
            - GRPC_GEN_ADDRESS=gen-service:3501
            - GRPC_COLLABORATION_ADDRESS=collaboration-service:3601
            - JWT_SECRET=very-important-please-change-it!
            - EMAIL_USER=${EMAIL_USER}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - REDIS_ADDRESS=redis:6379
            - S3_API_KEY=${S3_API_KEY}
            - S3_API_SECRET=${S3_API_SECRET}
            - S3_BUCKET=${S3_BUCKET}
            - S3_DOMAIN=${S3_DOMAIN}
            - S3_REGION=${S3_REGION}
        networks:
            - thinkflow
        depends_on:
            mysql:
                condition: service_healthy

    media-service:
        build: ./media-service
        environment:
            - DB_DSN=root:root_password_secret_tcp@tcp(mysql:3306)/thinkflow-media?charset=utf8mb4&parseTime=True&loc=Local
            - GIN_PORT=3400
            - GRPC_PORT=3401
            - GRPC_AUTH_ADDRESS=auth-service:3101
            - GRPC_USER_ADDRESS=user-service:3201
            - GRPC_NOTE_ADDRESS=note-service:3301
            - GRPC_GEN_ADDRESS=gen-service:3501
            - GRPC_COLLABORATION_ADDRESS=collaboration-service:3601
            - S3_API_KEY=${S3_API_KEY}
            - S3_API_SECRET=${S3_API_SECRET}
            - S3_BUCKET=${S3_BUCKET}
            - S3_DOMAIN=${S3_DOMAIN}
            - S3_REGION=${S3_REGION}
        networks:
            - thinkflow
        depends_on:
            mysql:
                condition: service_healthy

    gen-service:
        build: ./gen-service
        environment:
            - DB_DSN=root:root_password_secret_tcp@tcp(mysql:3306)/thinkflow-gen?charset=utf8mb4&parseTime=True&loc=Local
            - GIN_PORT=3500
            - GRPC_PORT=3501
            - GRPC_AUTH_ADDRESS=auth-service:3101
            - GRPC_USER_ADDRESS=user-service:3201
        networks:
            - thinkflow
        depends_on:
            mysql:
                condition: service_healthy

    collaboration-service:
        build: ./collaboration-service
        environment:
            - DB_DSN=root:root_password_secret_tcp@tcp(mysql:3306)/thinkflow-collaborations?charset=utf8mb4&parseTime=True&loc=Local
            - GIN_PORT=3600
            - GRPC_PORT=3601
            - GRPC_AUTH_ADDRESS=auth-service:3101
        networks:
            - thinkflow
        depends_on:
            mysql:
                condition: service_healthy

    notification-service:
        build: ./notification-service
        environment:
            - DB_DSN=root:root_password_secret_tcp@tcp(mysql:3306)/thinkflow-notifications?charset=utf8mb4&parseTime=True&loc=Local
            - GIN_PORT=3700
            - GRPC_PORT=3701
            - GRPC_AUTH_ADDRESS=auth-service:3101
            - NATS_SERVER=nats://nats:4222
            - NATS_USERNAME=${NATS_USERNAME}
            - NATS_PASSWORD=${NATS_PASSWORD}
            - NATS_TOKEN=${NATS_TOKEN}
        networks:
            - thinkflow
        depends_on:
            mysql:
                condition: service_healthy
            nats:
                condition: service_healthy

    ai-service:
        build: ./ai-service
        ports:
            - "5000:5000"
        environment:
            - PYTHONUNBUFFERED=True
            - PORT=5000
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
            - HUGGING_FACE_TOKEN_WRITE=${HUGGING_FACE_TOKEN_WRITE}
        networks:
            - thinkflow

    gateway:
        image: docker.tyk.io/tyk-gateway/tyk-gateway
        ports:
            - "8080:8080"
        volumes:
            - ./gateway/tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
            - ./gateway/apps:/opt/tyk-gateway/apps
        networks:
            - thinkflow
        depends_on:
            redis:
                condition: service_healthy

    grafana:
        image: grafana/grafana:11.2.0
        ports:
            - "3000:3000"
        container_name: grafana
        restart: unless-stopped
        networks:
            - thinkflow
        volumes:
            - grafana:/var/lib/grafana
            - ./grafana.ini:/etc/grafana/grafana.ini

    # Install prometheus and node-exporter
    prometheus:
        image: prom/prometheus:v2.48.0
        ports:
            - "9090:9090"
        networks:
            - thinkflow
        volumes:
            - prometheus:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    exporter:
        image: prom/node-exporter:latest
        container_name: exporter
        ports:
            - "9100:9100"
        networks:
            - thinkflow
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
            - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"

networks:
    thinkflow:
        driver: bridge

volumes:
    mysql:
    redis:
    grafana:
    prometheus:
