// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: proto/gen.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTranscriptByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Using int32 for compatibility with proto conventions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscriptByIdReq) Reset() {
	*x = GetTranscriptByIdReq{}
	mi := &file_proto_gen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscriptByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscriptByIdReq) ProtoMessage() {}

func (x *GetTranscriptByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscriptByIdReq.ProtoReflect.Descriptor instead.
func (*GetTranscriptByIdReq) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{0}
}

func (x *GetTranscriptByIdReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NewTranscriptIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTranscriptIdResp) Reset() {
	*x = NewTranscriptIdResp{}
	mi := &file_proto_gen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTranscriptIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTranscriptIdResp) ProtoMessage() {}

func (x *NewTranscriptIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTranscriptIdResp.ProtoReflect.Descriptor instead.
func (*NewTranscriptIdResp) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{1}
}

func (x *NewTranscriptIdResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PublicTranscriptInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicTranscriptInfo) Reset() {
	*x = PublicTranscriptInfo{}
	mi := &file_proto_gen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicTranscriptInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicTranscriptInfo) ProtoMessage() {}

func (x *PublicTranscriptInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicTranscriptInfo.ProtoReflect.Descriptor instead.
func (*PublicTranscriptInfo) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{2}
}

func (x *PublicTranscriptInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicTranscriptInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PublicTranscriptInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transcript    *PublicTranscriptInfo  `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"` // Singular response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicTranscriptInfoResp) Reset() {
	*x = PublicTranscriptInfoResp{}
	mi := &file_proto_gen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicTranscriptInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicTranscriptInfoResp) ProtoMessage() {}

func (x *PublicTranscriptInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicTranscriptInfoResp.ProtoReflect.Descriptor instead.
func (*PublicTranscriptInfoResp) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{3}
}

func (x *PublicTranscriptInfoResp) GetTranscript() *PublicTranscriptInfo {
	if x != nil {
		return x.Transcript
	}
	return nil
}

type GetSummaryByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Using int32 for compatibility with proto conventions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryByIdReq) Reset() {
	*x = GetSummaryByIdReq{}
	mi := &file_proto_gen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryByIdReq) ProtoMessage() {}

func (x *GetSummaryByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryByIdReq.ProtoReflect.Descriptor instead.
func (*GetSummaryByIdReq) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{4}
}

func (x *GetSummaryByIdReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NewSummaryIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSummaryIdResp) Reset() {
	*x = NewSummaryIdResp{}
	mi := &file_proto_gen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSummaryIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSummaryIdResp) ProtoMessage() {}

func (x *NewSummaryIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSummaryIdResp.ProtoReflect.Descriptor instead.
func (*NewSummaryIdResp) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{5}
}

func (x *NewSummaryIdResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PublicSummaryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SummaryText   string                 `protobuf:"bytes,2,opt,name=summary_text,json=summaryText,proto3" json:"summary_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicSummaryInfo) Reset() {
	*x = PublicSummaryInfo{}
	mi := &file_proto_gen_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicSummaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicSummaryInfo) ProtoMessage() {}

func (x *PublicSummaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicSummaryInfo.ProtoReflect.Descriptor instead.
func (*PublicSummaryInfo) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{6}
}

func (x *PublicSummaryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicSummaryInfo) GetSummaryText() string {
	if x != nil {
		return x.SummaryText
	}
	return ""
}

type PublicSummaryInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *PublicSummaryInfo     `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"` // Singular response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicSummaryInfoResp) Reset() {
	*x = PublicSummaryInfoResp{}
	mi := &file_proto_gen_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicSummaryInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicSummaryInfoResp) ProtoMessage() {}

func (x *PublicSummaryInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicSummaryInfoResp.ProtoReflect.Descriptor instead.
func (*PublicSummaryInfoResp) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{7}
}

func (x *PublicSummaryInfoResp) GetSummary() *PublicSummaryInfo {
	if x != nil {
		return x.Summary
	}
	return nil
}

type GetMindmapByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Using int32 for compatibility with proto conventions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMindmapByIdReq) Reset() {
	*x = GetMindmapByIdReq{}
	mi := &file_proto_gen_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMindmapByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMindmapByIdReq) ProtoMessage() {}

func (x *GetMindmapByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMindmapByIdReq.ProtoReflect.Descriptor instead.
func (*GetMindmapByIdReq) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{8}
}

func (x *GetMindmapByIdReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NewMindmapIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMindmapIdResp) Reset() {
	*x = NewMindmapIdResp{}
	mi := &file_proto_gen_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMindmapIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMindmapIdResp) ProtoMessage() {}

func (x *NewMindmapIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMindmapIdResp.ProtoReflect.Descriptor instead.
func (*NewMindmapIdResp) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{9}
}

func (x *NewMindmapIdResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PublicMindmapInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MindmapData   string                 `protobuf:"bytes,2,opt,name=mindmap_data,json=mindmapData,proto3" json:"mindmap_data,omitempty"` // JSON string containing mindmap data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicMindmapInfo) Reset() {
	*x = PublicMindmapInfo{}
	mi := &file_proto_gen_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicMindmapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicMindmapInfo) ProtoMessage() {}

func (x *PublicMindmapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicMindmapInfo.ProtoReflect.Descriptor instead.
func (*PublicMindmapInfo) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{10}
}

func (x *PublicMindmapInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicMindmapInfo) GetMindmapData() string {
	if x != nil {
		return x.MindmapData
	}
	return ""
}

type PublicMindmapInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mindmap       *PublicMindmapInfo     `protobuf:"bytes,1,opt,name=mindmap,proto3" json:"mindmap,omitempty"` // Singular response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicMindmapInfoResp) Reset() {
	*x = PublicMindmapInfoResp{}
	mi := &file_proto_gen_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicMindmapInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicMindmapInfoResp) ProtoMessage() {}

func (x *PublicMindmapInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gen_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicMindmapInfoResp.ProtoReflect.Descriptor instead.
func (*PublicMindmapInfoResp) Descriptor() ([]byte, []int) {
	return file_proto_gen_proto_rawDescGZIP(), []int{11}
}

func (x *PublicMindmapInfoResp) GetMindmap() *PublicMindmapInfo {
	if x != nil {
		return x.Mindmap
	}
	return nil
}

var File_proto_gen_proto protoreflect.FileDescriptor

var file_proto_gen_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a,
	0x13, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x54, 0x0a, 0x18, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x38, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x22, 0x23, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x22, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x11, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x54, 0x65, 0x78, 0x74, 0x22, 0x48, 0x0a,
	0x15, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x69,
	0x6e, 0x64, 0x6d, 0x61, 0x70, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x10,
	0x4e, 0x65, 0x77, 0x4d, 0x69, 0x6e, 0x64, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x46, 0x0a, 0x11, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4d, 0x69, 0x6e, 0x64, 0x6d, 0x61,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x64, 0x6d, 0x61, 0x70,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x69, 0x6e,
	0x64, 0x6d, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x15, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4d, 0x69, 0x6e, 0x64, 0x6d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2f, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x64, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4d, 0x69,
	0x6e, 0x64, 0x6d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x64, 0x6d,
	0x61, 0x70, 0x32, 0x60, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x18, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x32, 0x54, 0x0a, 0x0e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x32, 0x54, 0x0a, 0x0e, 0x4d, 0x69,
	0x6e, 0x64, 0x6d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x64, 0x6d, 0x61, 0x70, 0x42, 0x79, 0x49, 0x64, 0x12, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x64, 0x6d, 0x61, 0x70, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4d, 0x69, 0x6e, 0x64, 0x6d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x05, 0x5a, 0x03, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_gen_proto_rawDescOnce sync.Once
	file_proto_gen_proto_rawDescData []byte
)

func file_proto_gen_proto_rawDescGZIP() []byte {
	file_proto_gen_proto_rawDescOnce.Do(func() {
		file_proto_gen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gen_proto_rawDesc), len(file_proto_gen_proto_rawDesc)))
	})
	return file_proto_gen_proto_rawDescData
}

var file_proto_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_gen_proto_goTypes = []any{
	(*GetTranscriptByIdReq)(nil),     // 0: pb.GetTranscriptByIdReq
	(*NewTranscriptIdResp)(nil),      // 1: pb.NewTranscriptIdResp
	(*PublicTranscriptInfo)(nil),     // 2: pb.PublicTranscriptInfo
	(*PublicTranscriptInfoResp)(nil), // 3: pb.PublicTranscriptInfoResp
	(*GetSummaryByIdReq)(nil),        // 4: pb.GetSummaryByIdReq
	(*NewSummaryIdResp)(nil),         // 5: pb.NewSummaryIdResp
	(*PublicSummaryInfo)(nil),        // 6: pb.PublicSummaryInfo
	(*PublicSummaryInfoResp)(nil),    // 7: pb.PublicSummaryInfoResp
	(*GetMindmapByIdReq)(nil),        // 8: pb.GetMindmapByIdReq
	(*NewMindmapIdResp)(nil),         // 9: pb.NewMindmapIdResp
	(*PublicMindmapInfo)(nil),        // 10: pb.PublicMindmapInfo
	(*PublicMindmapInfoResp)(nil),    // 11: pb.PublicMindmapInfoResp
}
var file_proto_gen_proto_depIdxs = []int32{
	2,  // 0: pb.PublicTranscriptInfoResp.transcript:type_name -> pb.PublicTranscriptInfo
	6,  // 1: pb.PublicSummaryInfoResp.summary:type_name -> pb.PublicSummaryInfo
	10, // 2: pb.PublicMindmapInfoResp.mindmap:type_name -> pb.PublicMindmapInfo
	0,  // 3: pb.TranscriptService.GetTranscriptById:input_type -> pb.GetTranscriptByIdReq
	4,  // 4: pb.SummaryService.GetSummaryById:input_type -> pb.GetSummaryByIdReq
	8,  // 5: pb.MindmapService.GetMindmapById:input_type -> pb.GetMindmapByIdReq
	3,  // 6: pb.TranscriptService.GetTranscriptById:output_type -> pb.PublicTranscriptInfoResp
	7,  // 7: pb.SummaryService.GetSummaryById:output_type -> pb.PublicSummaryInfoResp
	11, // 8: pb.MindmapService.GetMindmapById:output_type -> pb.PublicMindmapInfoResp
	6,  // [6:9] is the sub-list for method output_type
	3,  // [3:6] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_gen_proto_init() }
func file_proto_gen_proto_init() {
	if File_proto_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gen_proto_rawDesc), len(file_proto_gen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_gen_proto_goTypes,
		DependencyIndexes: file_proto_gen_proto_depIdxs,
		MessageInfos:      file_proto_gen_proto_msgTypes,
	}.Build()
	File_proto_gen_proto = out.File
	file_proto_gen_proto_goTypes = nil
	file_proto_gen_proto_depIdxs = nil
}
